<!DOCTYPE HTML>
<html>

<head>
  <title>${page.title}</title>
  <meta name="description" content="Generated by make-your-site, odsek za primenjene računarske nauke i informatiku, FTN Novi Sad" />
  <meta name="keywords" content="make-your-site, festival nauke" />
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" type="text/css" href="style/style.css" />
</head>

<body>
  <div id="main">
    <div id="header">
      <div id="logo">
        <div class="banner"><img src="style/banner_boy.png"/></div>
      </div>
      <div id="menubar">
        <ul id="menu">
          <!-- put class="current" in the li tag for the selected page - to highlight which page you're on -->
          <li<#if isRoot> class="current"</#if>><a href="index.html">${rootPage.title}</a></li>
          <#list mainLinks as link>
          <li<#if link==page.title> class="current"</#if>><a href="${link}.html">${link}</a></li>
          </#list>
        </ul>
      </div>
    </div>
    <div id="site_content">
      <#if !isRoot && sidebarLinks?has_content>
      <div id="sidebar_container">
        <img class="paperclip" src="style/paperclip.png" alt="paperclip" />
        <div class="sidebar">
        <!-- insert your sidebar items here -->
        <ul id="menu">
          <#list sidebarLinks as link>
          <li><a href="${link}.html">${link}</a></li>
          </#list>
        </ul>        
        </div>
      </div>
      </#if>
      <div id="content">
        <h1>${page.title}</h1>
        <#if page.containsPicture()><img src="images/${page.picture.pictureName}" /></#if>
        ${page.content}
      </div>
    </div>
    <div id="footer">
      <p>Copyright &copy; Одсек за примењене рачунарске науке и информатику, <a href="http://www.ftn.uns.ac.rs/">Факултет техничких наука</a></p>
        <p>CSS шаблон преузет са <a href="http://www.html5webtemplates.co.uk">HTML5webtemplates.co.uk</a> и модификован за потребе апликације</p>
    </div>
  </div>
</body>
</html>
